# Generated by Django 5.2.3 on 2025-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
