# Generated by Django 5.2.3 on 2025-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0002_remove_vehicle_image_vehicle_image1_vehicle_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=20),
        ),
    ]
