# Generated by Django 5.2.3 on 2025-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0003_alter_vehicle_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_desc',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
