# Generated by Django 5.2.3 on 2025-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0004_booking_booking_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
