# Generated by Django 5.2.3 on 2025-08-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0006_alter_booking_booking_desc_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
    ]
