# Generated by Django 5.2.3 on 2025-08-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0007_remove_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
