# Generated by Django 5.2.3 on 2025-08-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roto', '0008_remove_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
