# Generated by Django 5.2.5 on 2025-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roto", "0009_booking_booking_id_booking_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
